name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  dio: ^5.1.2
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
