name: activities_repository
description: Dart package which manages the activities domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  equatable: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
